NumPy provides a multidimensional array object.

Each object comes with an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

Basically, you can use NumPy to create ndarray (N-dimensional array) and easily manipulate the array. It is super fast because it is written in C.

How is it different from Python arrays?

Python lists can be modified – you can add and remove elements. NumPy arrays have a fixed size at creation.

Python lists can contain different data types. NumPy arrays can only have one data type. If you put in mixed types, they become a string.

NumPy arrays come prepackaged with advanced mathematical operations. The operations are super fast even on large numbers of data and they use less memory.

Why use NumPy

Most data analysis programs use NumPy to manipulate data. They might take in data as standard Python lists, but they convert it to a NumPy array and manipulate the data using NumPy routines and output the transformed data as a NumPy array.

NumPy data array is the main data type used in most scientific and mathematical Python-based packages.

In [2]:
import numpy as np
# Example
squared_values = []
for number in range(10):
    squared_values.append(number*number)
print(squared_values)

vector = np.array(range(10))
scalar = 5
print(vector * vector)
print(scalar * scalar)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[ 0  1  4  9 16 25 36 49 64 81]
25


Numpy Casting - Converts Python List to Numpy Array

In [3]:
my_list = [1, 2, 3]
print(my_list)

import numpy as np

my_vector = np.array(my_list)
print(my_vector)

my_matrix = np.array([my_list, my_list])
np.hstack([my_list, my_list])

my_nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix = np.array(my_nested_list)
print(my_matrix)

my_list1 = [[1,2], [3,4]]
my_list2 = [[5,6], [7,8]]  
np.hstack([my_list1, my_list2])   
np.vstack([my_list1, my_list2])




[1, 2, 3]
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Numpy_ Creating arrays

In [4]:
import numpy as np
my_list = range(10)
## Create the array using arrange
np.arange(10)
np.arange(0, 10)
np.arange(0, 10, 2)

## Create arrays with zeros
np.zeros(3)
np.zeros((3, 3))

## Create arrays of ones
np.ones(3)
np.ones((3, 3))
np.ones(3) *  4
## Create evenly spaced vector
### Example use case: when you have Y values for a plot but need to generate X values
### *** Includes both start an end 
# np.arange(start, end(not included), step size)
# np.linspace(start, end(included), number_of_points)
np.linspace(0, 10, 5)
np.linspace(1900, 2000, 11)

array([1900., 1910., 1920., 1930., 1940., 1950., 1960., 1970., 1980.,
       1990., 2000.])

In [5]:
#Create an indentify matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# Creating an Empty Matrix
np.empty((2, 3))

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [4.9e-324, 9.9e-324, 1.5e-323]])

In [7]:
# Creating Random Numbers
#Uniform Distribution
np.random.rand(3)
np.random.rand(3,3)
# Normal distribution
np.random.randn(3)
np.random.randn(3,3)
# Random integers
# np.random.randint(start, end(not_included), size)
np.random.randint(1,101)
np.random.randint(1,101,5)  

array([56, 90, 20, 98, 29])

In [8]:
vector = np.arange(1, 10)
print(vector.reshape(3, 3))
vector = np.arange(1,13)
print(vector.reshape(3,4))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Basic Array Operations

In [9]:
#Basic Array operations
vector = np.random.randint(1, 50, 25)
#Min
vector.min()
# Max
vector.max()
# Get location of min value
index = vector.argmin()
# Get location of max value
index = vector.argmax
#Get Shape
vector.shape

my_matrix = vector.reshape(5, 5)
my_matrix.shape

(5, 5)

Indexing a 1D Array Vector

In [10]:
vector = np.array(range(10))
# vector[index]
# vector [start:end]
# vector [:end]
# vector [start:]
# vector [start, end, step]
vector[3]
vector[3:8]
vector[:5]
vector[5:]
vector[3:9:2]
vector[-1]


9

15.1.8. Setting multiple values at once – Broadcasting
There are two main features of NumPy arrays

Broadcasting – set multiple values at once

Vectorization – no need for explicit looping – example, vector multiplication or squaring



In [11]:
vector[3:6] = 12

If you store a slice of an array in a new variable, changes in the new variable will be reflected in the original array.

In [12]:
vector = np.array(range(10))
my_slice = vector[3:7]
my_slice[:] = 20
print(vector)

[ 0  1  2 20 20 20 20  7  8  9]


In [13]:
vector = np.array(range(10))
my_slice_copy = vector[3:7].copy()
print(vector)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
matrix = np.array(range(1,10)).reshape((3,3))
matrix[0,0]
matrix[0][0]
matrix[2,2]
matrix[2][2]


matrix[:,2] # Grab the third column
matrix[1,:] # Grab the second row
matrix[:2] # grab the first two rows, all columns
matrix[:2,:] # grab the first two rows, all columns
matrix[:,1:] # grab all the rows, but columns starting from 1

array([[2, 3],
       [5, 6],
       [8, 9]])

Conditional Selection

In [15]:
vector = np.arange(10)
gt2 = vector > 2
lt8 = vector < 8

selected_gt2 = vector[gt2]
selected_lt8 = vector[lt8]

vector[vector > 2]
vector[vector < 8]

cond = (vector>2) & (vector<7)
vector[cond]

cond = (vector>=2) & (vector<=7)
vector[cond]

array([2, 3, 4, 5, 6, 7])

Array Opeations

In [16]:
vector = np.arange(10)

vector + vector
vector - vector
vector * vector
vector / vector # problem!!! return `nan`
vector + 10
vector - 10
vector * 10
vector / 10

/var/folders/r5/_bzgrbtj6tg33lk21qcyg0l80000gn/T/ipykernel_11515/325426557.py:6: RuntimeWarning: invalid value encountered in divide
  vector / vector # problem!!! return `nan`


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [17]:
vector = np.arange(10)
np.max(vector)
np.min(vector)
np.sqrt(vector)
np.log(vector)

sum(vector<5)
import math
vector = np.arange(1, 10) * math.pi
np.sin(vector)
vector = np.arange(0, math.pi + math.pi/4, math.pi/4)
np.sin(vector)

matrix = np.random.rand(5, 5)
np.floor(matrix * 1000) / 1000
np.round(matrix*1000)/1000
np.ceil(matrix*1000)/1000

matrix = np.arange(1,10).reshape(3,3)
matrix.sum(axis=1)
matrix.sum(axis=0)
matrix.cumsum()
matrix.cumprod()

matrix.min(axis=1)
matrix.min(axis=0)

matrix.max(axis=1)
matrix.max(axis=0)

matrix = np.array([1,2,3]*3).reshape(3,3)
np.unique(matrix.reshape(3,3))

/var/folders/r5/_bzgrbtj6tg33lk21qcyg0l80000gn/T/ipykernel_11515/3991262562.py:5: RuntimeWarning: divide by zero encountered in log
  np.log(vector)


array([1, 2, 3])

Pandas
Built-on top of NumPy – meaning the underlying data structure used is ndarray

Pandas provides series which are like NumPy arrays but with associated index labels – meaning are like column labels or row labels. Element data type can be different

Pandas also provides dataframes which are like Excel sheets or database tables

In [18]:
import numpy as np
import pandas as pd

header = ['chrom', 'pos', 'filter']
data = [4, 12345, 38.4]

vector = np.array(data)
data_dict = {'chrom': 4, 'pos': 12345, 'filter': 38.4}

s1 = pd.Series(data=data) # Notice the data type is float
s2 = pd.Series(data=data, index=header)

# can also do
s1 = pd.Series(data)
s2 = pd.Series(data, header)

# can hold different data types

data = [1, '2s', 34]
pd.Series(data)

# can use a dictionary to initialize a panda series
pd.Series(data_dict)

## Using index labels to fetch element
header = ['chrom', 'pos', 'filter']
data = [4, 12345, 38.4]
series = pd.Series(data=data, index=header)
series['chrom']
series['filter']

series = pd.Series(data)
series[0]

4.0

In [19]:
## Basic operations
header1 = ['chrom', 'pos', 'filter']
data1 = [4, 12345, 38.4]
header2 = ['chrom', 'pos', 'filter', 'qual']
data2 = [3, 4899, 234, 89.9]

s1 = pd.Series(data1, header1)
s2 = pd.Series(data2, header2)
s1 + s2

chrom         7.0
filter      272.4
pos       17244.0
qual          NaN
dtype: float64

In [20]:
header1 = ['chrom', 'pos', 'filter']
data1 = [4, 12345, 38.4]
header2 = ['chrom', 'pos', 'filter', 'qual']
data2 = ['3', 4899, 234, 89.9]

s1 = pd.Series(data1, header1)
s2 = pd.Series(data2, header2)
s1 + s2

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [ ]:
data1 = [4, 12345, 38.4]
data2 = [3, 4899, 234, 89.9]

s1 = pd.Series(data1)
s2 = pd.Series(data2)


## IMPORTANT - with index labels -- operations are based on label
header1 = ['pos', 'filter', 'chrom']
data1 = [12345, 38.4, 4]
header2 = ['chrom', 'pos', 'filter', 'qual']
data2 = [3, 4899, 234, 89.9]

s1 = pd.Series(data1, header1)
s2 = pd.Series(data2, header2)
s1 + s2


data1 = [12345, 38.4, 4]
data2 = [3, 4899, 234, 89.9]

s1 = pd.Series(data1)
s2 = pd.Series(data2)

DataFrames

In [ ]:
import numpy as np
import pandas as pd

header = ['exam1', 'exam2', 'exam3']
data = np.random.randint(83, 12345, 12).reshape(4, 3)
students = ['students1', 'students2', 'students3', 'students4']

df = pd.DataFrame(data=data, columns=header1)

df = pd.DataFrame(data=data, index=students, columns=header)
df['exam1']
df.exam1 # not a good way to do this

print(df)

           exam1  exam2  exam3
students1  10666   5013  10252
students2   1244  11215   5753
students3   6478   8128   9794
students4   5517   6729    731


In [ ]:
df['average'] = (df['exam1'] + df['exam2'] + df['exam3'])/3
df

exam1  exam2  exam3      average
students1  10666   5013  10252  8643.666667
students2   1244  11215   5753  6070.666667
students3   6478   8128   9794  8133.333333
students4   5517   6729    731  4325.666667

In [ ]:
df.drop('students3')

exam1  exam2  exam3      average
students1  10666   5013  10252  8643.666667
students2   1244  11215   5753  6070.666667
students4   5517   6729    731  4325.666667

In [ ]:
header = ['exam1', 'exam2', 'exam3']
data = np.random.randint(65, 101, 12).reshape(4,3)
students = ['student1', 'student2', 'student3', 'student4']
df = pd.DataFrame(data=data, index=students, columns=header)

df.loc['student1']
df.iloc[0] ## remember that column names do not count as rows

exam1    79
exam2    82
exam3    98
Name: student1, dtype: int64

Exercises

In [ ]:
import pandas as pd
import numpy as np
filename = '/Users/adityasrivatsav/Documents/GitHub/PYTHON/Basics/100-patients/PatientCorePopulatedTable.txt'

df = pd.read_csv(filename, delimiter='\t')
df

PatientID PatientGender  \
0   FB2ABB23-C9D0-4D09-8464-49BF0B982F0F          Male   
1   64182B95-EB72-4E2B-BE77-8050B71498CE          Male   
2   DB22A4D9-7E4D-485C-916A-9CD1386507FB        Female   
3   6E70D84D-C75F-477C-BC37-9177C3698C66          Male   
4   C8556CC0-32FC-4CA5-A8CD-9CCF38816167        Female   
..                                   ...           ...   
95  135C831F-7DA5-46C0-959C-EBCBD8810B43          Male   
96  8856096E-E59C-4156-A767-C091AF799C80        Female   
97  6623F5D6-D581-4268-9F9B-21612FBBF7B5        Female   
98  65A7FBE0-EA9F-49E9-9824-D8F3AD98DAC0        Female   
99  FB909FAE-72DD-4F6F-9828-D92183DF185F          Male   

         PatientDateOfBirth       PatientRace PatientMaritalStatus  \
0   1947-12-28 02:45:40.547           Unknown              Married   
1   1952-01-18 19:51:12.917  African American            Separated   
2   1970-07-25 13:04:20.717             Asian              Married   
3   1979-01-04 05:45:29.580             White              Married   
4   1921-04-11 11:39:49.197             White              Married   
..                      ...               ...                  ...   
95  1971-05-13 04:40:05.623             White              Unknown   
96  1988-11-25 02:59:36.373             White             Divorced   
97  1943-02-17 15:36:13.787             Asian               Single   
98  1962-11-30 06:28:33.110             White            Separated   
99  1940-07-15 12:18:41.080             White               Single   

   PatientLanguage  PatientPopulationPercentageBelowPoverty  
0        Icelandic                                    18.08  
1          English                                    13.03  
2          English                                     6.67  
3          English                                    16.09  
4          English                                    18.20  
..             ...                                      ...  
95         Spanish                                    12.38  
96         English                                    11.08  
97         Spanish                                    14.49  
98         Spanish                                    17.98  
99         Spanish                                    14.90  

[100 rows x 7 columns]

In [ ]:
df.head(10)

PatientID PatientGender  \
0  FB2ABB23-C9D0-4D09-8464-49BF0B982F0F          Male   
1  64182B95-EB72-4E2B-BE77-8050B71498CE          Male   
2  DB22A4D9-7E4D-485C-916A-9CD1386507FB        Female   
3  6E70D84D-C75F-477C-BC37-9177C3698C66          Male   
4  C8556CC0-32FC-4CA5-A8CD-9CCF38816167        Female   
5  7FD13988-E58A-4A5C-8680-89AC200950FA          Male   
6  C60FE675-CA52-4C55-A233-F4B27E94987F          Male   
7  B39DC5AC-E003-4E6A-91B6-FC07625A1285        Female   
8  FA157FA5-F488-4884-BF87-E144630D595C        Female   
9  B7E9FC4C-5182-4A34-954E-CEF5FC07E96D        Female   

        PatientDateOfBirth       PatientRace PatientMaritalStatus  \
0  1947-12-28 02:45:40.547           Unknown              Married   
1  1952-01-18 19:51:12.917  African American            Separated   
2  1970-07-25 13:04:20.717             Asian              Married   
3  1979-01-04 05:45:29.580             White              Married   
4  1921-04-11 11:39:49.197             White              Married   
5  1965-07-12 15:41:20.523             White              Married   
6  1957-10-30 23:26:15.303             Asian              Married   
7  1935-11-03 21:07:09.040             White              Married   
8  1932-11-01 06:19:56.577             White               Single   
9  1985-12-11 02:48:16.907           Unknown               Single   

  PatientLanguage  PatientPopulationPercentageBelowPoverty  
0       Icelandic                                    18.08  
1         English                                    13.03  
2         English                                     6.67  
3         English                                    16.09  
4         English                                    18.20  
5         Spanish                                    12.41  
6         Spanish                                    12.80  
7         English                                    15.31  
8         English                                    16.32  
9         English                                    11.43

In [ ]:
df.tail(10)

PatientID PatientGender  \
90  36E2F89E-777A-4D77-9D95-0D70A8AB416F          Male   
91  672D554B-D6D1-40B2-A6A4-21A4CB6B1AA6          Male   
92  03A481F5-B32A-4A91-BD42-43EB78FEBA77        Female   
93  2A5251B1-0945-47FA-A65C-7A6381562591        Female   
94  8AF47463-8534-4203-B210-C2290F6CE689        Female   
95  135C831F-7DA5-46C0-959C-EBCBD8810B43          Male   
96  8856096E-E59C-4156-A767-C091AF799C80        Female   
97  6623F5D6-D581-4268-9F9B-21612FBBF7B5        Female   
98  65A7FBE0-EA9F-49E9-9824-D8F3AD98DAC0        Female   
99  FB909FAE-72DD-4F6F-9828-D92183DF185F          Male   

         PatientDateOfBirth       PatientRace PatientMaritalStatus  \
90  1980-05-30 13:23:50.703  African American            Separated   
91  1983-06-17 04:46:13.753  African American               Single   
92  1968-02-07 23:02:38.017             Asian               Single   
93  1942-01-07 16:45:33.060           Unknown              Married   
94  1952-06-27 17:29:04.187             White             Divorced   
95  1971-05-13 04:40:05.623             White              Unknown   
96  1988-11-25 02:59:36.373             White             Divorced   
97  1943-02-17 15:36:13.787             Asian               Single   
98  1962-11-30 06:28:33.110             White            Separated   
99  1940-07-15 12:18:41.080             White               Single   

   PatientLanguage  PatientPopulationPercentageBelowPoverty  
90         English                                    19.36  
91       Icelandic                                    11.04  
92         Unknown                                    93.23  
93         Spanish                                    18.05  
94         English                                    11.88  
95         Spanish                                    12.38  
96         English                                    11.08  
97         Spanish                                    14.49  
98         Spanish                                    17.98  
99         Spanish                                    14.90

In [ ]:
df[50:60]

PatientID PatientGender  \
50  35FE7491-1A1D-48CB-810C-8DC2599AB3DD          Male   
51  868E700E-3C56-458F-A477-078D671DCB20        Female   
52  56A35E74-90BE-44A0-B7BA-7743BB152133        Female   
53  CC12B481-B516-455B-884F-4CA900B29F2E        Female   
54  714823AF-C52C-414C-B53B-C43EACD194C3          Male   
55  3231F930-2978-4F50-8234-755449851E7B          Male   
56  C2CCB1AB-6633-4CB3-B4E8-157E6FB02376        Female   
57  1311FEE4-2FDC-46E4-83D3-1550A3E51D2C        Female   
58  21792512-2D40-4326-BEA2-A40127EB24FF          Male   
59  EEAFC0B3-B835-4D99-AB33-2F9428E54E5F        Female   

         PatientDateOfBirth       PatientRace PatientMaritalStatus  \
50  1969-11-02 06:34:34.527             White              Married   
51  1978-09-21 15:29:44.770  African American              Married   
52  1968-11-09 15:29:19.557             White              Married   
53  1985-10-21 07:59:04.777           Unknown             Divorced   
54  1952-05-08 23:51:50.127             White              Married   
55  1979-05-26 04:58:10.627             White               Single   
56  1964-05-07 10:20:37.740             White               Single   
57  1988-03-28 03:09:22.807             White               Single   
58  1938-03-24 19:25:53.980             White               Single   
59  1961-01-08 15:19:15.490             Asian              Unknown   

   PatientLanguage  PatientPopulationPercentageBelowPoverty  
50         English                                     4.51  
51       Icelandic                                     5.94  
52         English                                     8.81  
53         English                                    14.58  
54         English                                    13.23  
55         English                                    18.36  
56         Spanish                                    15.98  
57         English                                    14.99  
58         Unknown                                    89.44  
59         English                                    18.95

In [ ]:
df[['PatientGender', 'PatientID']].head(10)

PatientGender                             PatientID
0          Male  FB2ABB23-C9D0-4D09-8464-49BF0B982F0F
1          Male  64182B95-EB72-4E2B-BE77-8050B71498CE
2        Female  DB22A4D9-7E4D-485C-916A-9CD1386507FB
3          Male  6E70D84D-C75F-477C-BC37-9177C3698C66
4        Female  C8556CC0-32FC-4CA5-A8CD-9CCF38816167
5          Male  7FD13988-E58A-4A5C-8680-89AC200950FA
6          Male  C60FE675-CA52-4C55-A233-F4B27E94987F
7        Female  B39DC5AC-E003-4E6A-91B6-FC07625A1285
8        Female  FA157FA5-F488-4884-BF87-E144630D595C
9        Female  B7E9FC4C-5182-4A34-954E-CEF5FC07E96D

In [ ]:
df[['PatientGender', 'PatientID']].rename(columns={'PatientGender':'Gender', 'PatientID': 'ID'})

Gender                                    ID
0     Male  FB2ABB23-C9D0-4D09-8464-49BF0B982F0F
1     Male  64182B95-EB72-4E2B-BE77-8050B71498CE
2   Female  DB22A4D9-7E4D-485C-916A-9CD1386507FB
3     Male  6E70D84D-C75F-477C-BC37-9177C3698C66
4   Female  C8556CC0-32FC-4CA5-A8CD-9CCF38816167
..     ...                                   ...
95    Male  135C831F-7DA5-46C0-959C-EBCBD8810B43
96  Female  8856096E-E59C-4156-A767-C091AF799C80
97  Female  6623F5D6-D581-4268-9F9B-21612FBBF7B5
98  Female  65A7FBE0-EA9F-49E9-9824-D8F3AD98DAC0
99    Male  FB909FAE-72DD-4F6F-9828-D92183DF185F

[100 rows x 2 columns]

In [ ]:
from IPython.display import display
import pandas as pd
import numpy as np
filename = '/Users/adityasrivatsav/Documents/GitHub/PYTHON/Basics/100-patients/PatientCorePopulatedTable.txt'

df = pd.read_csv(filename, delimiter='\t')
df


PatientID PatientGender  \
0   FB2ABB23-C9D0-4D09-8464-49BF0B982F0F          Male   
1   64182B95-EB72-4E2B-BE77-8050B71498CE          Male   
2   DB22A4D9-7E4D-485C-916A-9CD1386507FB        Female   
3   6E70D84D-C75F-477C-BC37-9177C3698C66          Male   
4   C8556CC0-32FC-4CA5-A8CD-9CCF38816167        Female   
..                                   ...           ...   
95  135C831F-7DA5-46C0-959C-EBCBD8810B43          Male   
96  8856096E-E59C-4156-A767-C091AF799C80        Female   
97  6623F5D6-D581-4268-9F9B-21612FBBF7B5        Female   
98  65A7FBE0-EA9F-49E9-9824-D8F3AD98DAC0        Female   
99  FB909FAE-72DD-4F6F-9828-D92183DF185F          Male   

         PatientDateOfBirth       PatientRace PatientMaritalStatus  \
0   1947-12-28 02:45:40.547           Unknown              Married   
1   1952-01-18 19:51:12.917  African American            Separated   
2   1970-07-25 13:04:20.717             Asian              Married   
3   1979-01-04 05:45:29.580             White              Married   
4   1921-04-11 11:39:49.197             White              Married   
..                      ...               ...                  ...   
95  1971-05-13 04:40:05.623             White              Unknown   
96  1988-11-25 02:59:36.373             White             Divorced   
97  1943-02-17 15:36:13.787             Asian               Single   
98  1962-11-30 06:28:33.110             White            Separated   
99  1940-07-15 12:18:41.080             White               Single   

   PatientLanguage  PatientPopulationPercentageBelowPoverty  
0        Icelandic                                    18.08  
1          English                                    13.03  
2          English                                     6.67  
3          English                                    16.09  
4          English                                    18.20  
..             ...                                      ...  
95         Spanish                                    12.38  
96         English                                    11.08  
97         Spanish                                    14.49  
98         Spanish                                    17.98  
99         Spanish                                    14.90  

[100 rows x 7 columns]

In [ ]:
df_new = df[['PatientID', 'PatientPopulationPercentageBelowPoverty']].copy()
df_new.rename(
    columns={
        'PatientID': 'PTID',
        'PatientPopulationPercentageBelowPoverty': 'Poverty Level'
    },
    inplace=True
)
#Adding the columns not from the table
df_new.insert(loc=1, column='Hospital', value='Buffalo Hospital')
df_new['Poverty Level'] = df_new['Poverty Level'] * 10
df_new.head(10)

PTID          Hospital  Poverty Level
0  FB2ABB23-C9D0-4D09-8464-49BF0B982F0F  Buffalo Hospital          180.8
1  64182B95-EB72-4E2B-BE77-8050B71498CE  Buffalo Hospital          130.3
2  DB22A4D9-7E4D-485C-916A-9CD1386507FB  Buffalo Hospital           66.7
3  6E70D84D-C75F-477C-BC37-9177C3698C66  Buffalo Hospital          160.9
4  C8556CC0-32FC-4CA5-A8CD-9CCF38816167  Buffalo Hospital          182.0
5  7FD13988-E58A-4A5C-8680-89AC200950FA  Buffalo Hospital          124.1
6  C60FE675-CA52-4C55-A233-F4B27E94987F  Buffalo Hospital          128.0
7  B39DC5AC-E003-4E6A-91B6-FC07625A1285  Buffalo Hospital          153.1
8  FA157FA5-F488-4884-BF87-E144630D595C  Buffalo Hospital          163.2
9  B7E9FC4C-5182-4A34-954E-CEF5FC07E96D  Buffalo Hospital          114.3

In [ ]:
pd.DataFrame(df['PatientMaritalStatus'].unique(), columns=['PatientMaritalStatus'])

PatientMaritalStatus
0              Married
1            Separated
2               Single
3             Divorced
4              Unknown
5              Widowed

In [ ]:
from IPython.display import display
import pandas as pd
import numpy as np
filename = '/Users/adityasrivatsav/Documents/GitHub/PYTHON/Basics/100-patients/PatientCorePopulatedTable.txt'

df = pd.read_csv(filename, delimiter='\t')
df[['PatientRace', 'PatientMaritalStatus']].drop_duplicates().sort_values(['PatientRace', 'PatientMaritalStatus']).reset_index(drop=True)

PatientRace PatientMaritalStatus
0   African American              Married
1   African American            Separated
2   African American               Single
3   African American              Unknown
4              Asian             Divorced
5              Asian              Married
6              Asian            Separated
7              Asian               Single
8              Asian              Unknown
9            Unknown             Divorced
10           Unknown              Married
11           Unknown               Single
12             White             Divorced
13             White              Married
14             White            Separated
15             White               Single
16             White              Unknown
17             White              Widowed

In [21]:
import pandas as pd

filename = '/Users/adityasrivatsav/Documents/GitHub/PYTHON/Basics/100-patients/AdmissionsDiagnosesCorePopulatedTable.txt'
df = pd.read_csv(filename, delimiter='\t')

In [22]:
pd.DataFrame(df[['PrimaryDiagnosisCode', 'PrimaryDiagnosisDescription']].apply(lambda row: f'({row[0]}) {row[1]}', axis=1), columns=['CodeWDescription'])

/var/folders/r5/_bzgrbtj6tg33lk21qcyg0l80000gn/T/ipykernel_11515/1055258946.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  pd.DataFrame(df[['PrimaryDiagnosisCode', 'PrimaryDiagnosisDescription']].apply(lambda row: f'({row[0]}) {row[1]}', axis=1), columns=['CodeWDescription'])


CodeWDescription
0    (M01.X) Direct infection of joint in infectiou...
1    (D65) Disseminated intravascular coagulation [...
2    (C92.1) Chronic myeloid leukemia, BCR/ABL-posi...
3    (M05.51) Rheumatoid polyneuropathy with rheuma...
4    (C91.00) Acute lymphoblastic leukemia not havi...
..                                                 ...
367                          (H15) Disorders of sclera
368  (M05.27) Rheumatoid vasculitis with rheumatoid...
369  (N16) Renal tubulo-interstitial disorders in d...
370         (D35.2) Benign neoplasm of pituitary gland
371  (F06.1) Catatonic disorder due to known physio...

[372 rows x 1 columns]

In [23]:
# Filtering data
from IPython import display
import pandas as pd
import numpy as np

filename = '/Users/adityasrivatsav/Documents/GitHub/PYTHON/Basics/100-patients/PatientCorePopulatedTable.txt'

df = pd.read_csv(filename, delimiter='\t')
mask = (
    (((df['PatientRace'] == 'White') & (df['PatientMaritalStatus'] == 'Married')) |
    ((df['PatientRace'] == 'African American') & (df['PatientMaritalStatus'] == 'Married'))) &
    (df['PatientPopulationPercentageBelowPoverty'] > 15)
)

df_new  = df[mask][['PatientID', 'PatientRace', 'PatientMaritalStatus', 'PatientPopulationPercentageBelowPoverty']].reset_index(drop=True)
df_new

PatientID       PatientRace  \
0   6E70D84D-C75F-477C-BC37-9177C3698C66             White   
1   C8556CC0-32FC-4CA5-A8CD-9CCF38816167             White   
2   B39DC5AC-E003-4E6A-91B6-FC07625A1285             White   
3   25B786AF-0F99-478C-9CFA-0EA607E45834             White   
4   81C5B13B-F6B2-4E57-9593-6E7E4C13B2CE             White   
5   69B5D2A0-12FD-46EF-A5FF-B29C4BAFBE49             White   
6   9BBF3A51-443D-438B-9289-B98B8E0577C0             White   
7   49DADA25-F2C2-42BB-8210-D78E6C7B0D48  African American   
8   2EE42DEF-37CA-4694-827E-FA4EAF882BFC             White   
9   C65A4ADE-112E-49E4-B72A-0DED22C242ED             White   
10  80AC01B2-BD55-4BE0-A59A-4024104CF4E9  African American   
11  0E0EADE8-5592-4E0B-9F88-D7596E32EE08             White   
12  BC44CE19-9FC5-4AC9-A296-9EBC5E3D03AE  African American   
13  3E462A8F-7B90-43A1-A8B6-AD82CB5002C9             White   

   PatientMaritalStatus  PatientPopulationPercentageBelowPoverty  
0               Married                                    16.09  
1               Married                                    18.20  
2               Married                                    15.31  
3               Married                                    93.60  
4               Married                                    19.22  
5               Married                                    18.65  
6               Married                                    16.76  
7               Married                                    19.50  
8               Married                                    18.91  
9               Married                                    19.66  
10              Married                                    19.74  
11              Married                                    18.80  
12              Married                                    15.04  
13              Married                                    18.33

In [24]:
df.query("((PatientRace == 'White' & PatientMaritalStatus == 'Married') | (PatientRace == 'African American' & PatientMaritalStatus == 'Married')) & PatientPopulationPercentageBelowPoverty > 15")

PatientID PatientGender  \
3   6E70D84D-C75F-477C-BC37-9177C3698C66          Male   
4   C8556CC0-32FC-4CA5-A8CD-9CCF38816167        Female   
7   B39DC5AC-E003-4E6A-91B6-FC07625A1285        Female   
18  25B786AF-0F99-478C-9CFA-0EA607E45834          Male   
23  81C5B13B-F6B2-4E57-9593-6E7E4C13B2CE        Female   
32  69B5D2A0-12FD-46EF-A5FF-B29C4BAFBE49          Male   
35  9BBF3A51-443D-438B-9289-B98B8E0577C0          Male   
38  49DADA25-F2C2-42BB-8210-D78E6C7B0D48          Male   
60  2EE42DEF-37CA-4694-827E-FA4EAF882BFC          Male   
64  C65A4ADE-112E-49E4-B72A-0DED22C242ED          Male   
65  80AC01B2-BD55-4BE0-A59A-4024104CF4E9        Female   
70  0E0EADE8-5592-4E0B-9F88-D7596E32EE08        Female   
79  BC44CE19-9FC5-4AC9-A296-9EBC5E3D03AE        Female   
82  3E462A8F-7B90-43A1-A8B6-AD82CB5002C9        Female   

         PatientDateOfBirth       PatientRace PatientMaritalStatus  \
3   1979-01-04 05:45:29.580             White              Married   
4   1921-04-11 11:39:49.197             White              Married   
7   1935-11-03 21:07:09.040             White              Married   
18  1926-08-20 00:21:38.870             White              Married   
23  1930-05-28 02:59:42.857             White              Married   
32  1954-05-02 16:38:15.957             White              Married   
35  1944-11-25 06:12:56.860             White              Married   
38  1962-04-08 10:18:26.263  African American              Married   
60  1964-04-27 00:41:40.410             White              Married   
64  1955-04-07 18:55:17.077             White              Married   
65  1965-05-14 15:25:09.740  African American              Married   
70  1942-07-13 21:15:37.517             White              Married   
79  1953-06-04 03:16:17.843  African American              Married   
82  1986-12-20 16:41:34.793             White              Married   

   PatientLanguage  PatientPopulationPercentageBelowPoverty  
3          English                                    16.09  
4          English                                    18.20  
7          English                                    15.31  
18         English                                    93.60  
23       Icelandic                                    19.22  
32         English                                    18.65  
35         English                                    16.76  
38         English                                    19.50  
60         English                                    18.91  
64         English                                    19.66  
65         English                                    19.74  
70         Spanish                                    18.80  
79         English                                    15.04  
82         Spanish                                    18.33

In [30]:
from IPython.display import display
import pandas as pd
import numpy as np
filename = '/Users/adityasrivatsav/Documents/GitHub/PYTHON/Basics/100-patients/PatientCorePopulatedTable.txt'

df = pd.read_csv(filename, delimiter='\t')
df_new = df[
    ['PatientMaritalStatus', 'PatientPopulationPercentageBelowPoverty']
].sort_values(['PatientPopulationPercentageBelowPoverty']).reset_index(drop=True)
display(df_new)


PatientMaritalStatus  PatientPopulationPercentageBelowPoverty
0                Single                                     1.70
1               Married                                     3.30
2               Married                                     4.34
3               Married                                     4.51
4               Married                                     5.94
..                  ...                                      ...
95               Single                                    93.23
96              Married                                    93.60
97               Single                                    94.00
98              Married                                    94.06
99            Separated                                    98.40

[100 rows x 2 columns]

In [31]:
#Filtering
from IPython.display import display
import pandas as pd
import numpy as np
filename = '/Users/adityasrivatsav/Documents/GitHub/PYTHON/Basics/100-patients/PatientCorePopulatedTable.txt'

df = pd.read_csv(filename, delimiter='\t')
cond = (df['PatientGender'] == 'Male') & (df['PatientDateOfBirth'] < '1950-01-01')
df_new = df[cond].reset_index(drop=True).sort_values('PatientDateOfBirth')
display(df_new)

PatientID PatientGender  \
14  DDC0BC57-7A4E-4E02-9282-177750B74FBC          Male   
10  53B9FFDD-F80B-43BE-93CF-C34A023EE7E9          Male   
2   DA6CECFF-DE13-4C4C-919F-64E1A2B76C9D          Male   
3   7C788499-7798-484B-A027-9FCDC4C0DADB          Male   
4   25B786AF-0F99-478C-9CFA-0EA607E45834          Male   
13  4C201C71-CCED-40D1-9642-F9C8C485B854          Male   
8   A0A976C8-9B30-4492-B8C4-5B25095B9192          Male   
15  1A220558-5996-43E1-AE5D-7B96180FED35          Male   
12  21792512-2D40-4326-BEA2-A40127EB24FF          Male   
11  C5D09468-574F-4802-B56F-DB38F4EB1687          Male   
16  FB909FAE-72DD-4F6F-9828-D92183DF185F          Male   
5   FFCDECD6-4048-4DCB-B910-1218160005B3          Male   
7   9BBF3A51-443D-438B-9289-B98B8E0577C0          Male   
9   E483DE6E-D4E6-47FD-905B-22EE86EC7ACE          Male   
6   967987B9-FFEF-4776-85CF-AE05CA81F583          Male   
0   FB2ABB23-C9D0-4D09-8464-49BF0B982F0F          Male   
1   1A40AF35-C6D4-4D46-B475-A15D84E8A9D5          Male   

         PatientDateOfBirth       PatientRace PatientMaritalStatus  \
14  1921-03-26 14:38:51.803             White               Single   
10  1921-08-22 19:17:09.227             White             Divorced   
2   1924-06-27 19:37:58.823             Asian             Divorced   
3   1926-08-13 10:22:16.247             White              Married   
4   1926-08-20 00:21:38.870             White              Married   
13  1926-09-22 09:17:14.713  African American              Married   
8   1931-05-26 14:54:15.847             Asian               Single   
15  1937-09-07 22:23:53.143             Asian              Married   
12  1938-03-24 19:25:53.980             White               Single   
11  1939-07-07 19:39:49.753  African American              Married   
16  1940-07-15 12:18:41.080             White               Single   
5   1941-05-06 14:56:42.687             White               Single   
7   1944-11-25 06:12:56.860             White              Married   
9   1945-11-18 04:14:31.573  African American               Single   
6   1947-02-13 10:26:55.520             White              Widowed   
0   1947-12-28 02:45:40.547           Unknown              Married   
1   1949-01-10 15:37:35.543             White              Married   

   PatientLanguage  PatientPopulationPercentageBelowPoverty  
14         English                                    18.41  
10       Icelandic                                    18.17  
2          English                                    83.75  
3          English                                    11.89  
4          English                                    93.60  
13         English                                    10.30  
8          English                                    19.52  
15         English                                    15.11  
12         Unknown                                    89.44  
11       Icelandic                                    10.87  
16         Spanish                                    14.90  
5          English                                    14.49  
7          English                                    16.76  
9          English                                    16.88  
6          English                                    88.66  
0        Icelandic                                    18.08  
1          English                                    11.25

In [33]:
#Filtering
from IPython.display import display
import pandas as pd
import numpy as np
filename = '/Users/adityasrivatsav/Documents/GitHub/PYTHON/Basics/100-patients/PatientCorePopulatedTable.txt'

df = pd.read_csv(filename, delimiter='\t')
cond = ((df['PatientGender'] == 'Male') | (df['PatientRace'] == 'White')) & (df['PatientDateOfBirth'] < '1950-01-01')
df_new = df[cond].reset_index(drop=True).sort_values('PatientDateOfBirth')
display(df_new)

PatientID PatientGender  \
20  DDC0BC57-7A4E-4E02-9282-177750B74FBC          Male   
1   C8556CC0-32FC-4CA5-A8CD-9CCF38816167        Female   
15  53B9FFDD-F80B-43BE-93CF-C34A023EE7E9          Male   
5   DA6CECFF-DE13-4C4C-919F-64E1A2B76C9D          Male   
6   7C788499-7798-484B-A027-9FCDC4C0DADB          Male   
7   25B786AF-0F99-478C-9CFA-0EA607E45834          Male   
18  4C201C71-CCED-40D1-9642-F9C8C485B854          Male   
8   81C5B13B-F6B2-4E57-9593-6E7E4C13B2CE        Female   
13  A0A976C8-9B30-4492-B8C4-5B25095B9192          Male   
3   FA157FA5-F488-4884-BF87-E144630D595C        Female   
2   B39DC5AC-E003-4E6A-91B6-FC07625A1285        Female   
23  1A220558-5996-43E1-AE5D-7B96180FED35          Male   
12  80D356B4-F974-441F-A5F2-F95986D119A2        Female   
17  21792512-2D40-4326-BEA2-A40127EB24FF          Male   
16  C5D09468-574F-4802-B56F-DB38F4EB1687          Male   
24  FB909FAE-72DD-4F6F-9828-D92183DF185F          Male   
9   FFCDECD6-4048-4DCB-B910-1218160005B3          Male   
19  0E0EADE8-5592-4E0B-9F88-D7596E32EE08        Female   
22  66154E24-D3EE-4311-89DB-6195278F9B3C        Female   
11  9BBF3A51-443D-438B-9289-B98B8E0577C0          Male   
21  E250799D-F6DE-4914-ADB4-B08A6E5029B9        Female   
14  E483DE6E-D4E6-47FD-905B-22EE86EC7ACE          Male   
10  967987B9-FFEF-4776-85CF-AE05CA81F583          Male   
0   FB2ABB23-C9D0-4D09-8464-49BF0B982F0F          Male   
4   1A40AF35-C6D4-4D46-B475-A15D84E8A9D5          Male   

         PatientDateOfBirth       PatientRace PatientMaritalStatus  \
20  1921-03-26 14:38:51.803             White               Single   
1   1921-04-11 11:39:49.197             White              Married   
15  1921-08-22 19:17:09.227             White             Divorced   
5   1924-06-27 19:37:58.823             Asian             Divorced   
6   1926-08-13 10:22:16.247             White              Married   
7   1926-08-20 00:21:38.870             White              Married   
18  1926-09-22 09:17:14.713  African American              Married   
8   1930-05-28 02:59:42.857             White              Married   
13  1931-05-26 14:54:15.847             Asian               Single   
3   1932-11-01 06:19:56.577             White               Single   
2   1935-11-03 21:07:09.040             White              Married   
23  1937-09-07 22:23:53.143             Asian              Married   
12  1938-03-06 18:24:18.297             White               Single   
17  1938-03-24 19:25:53.980             White               Single   
16  1939-07-07 19:39:49.753  African American              Married   
24  1940-07-15 12:18:41.080             White               Single   
9   1941-05-06 14:56:42.687             White               Single   
19  1942-07-13 21:15:37.517             White              Married   
22  1944-08-26 13:03:24.297             White             Divorced   
11  1944-11-25 06:12:56.860             White              Married   
21  1945-08-04 19:03:00.757             White               Single   
14  1945-11-18 04:14:31.573  African American               Single   
10  1947-02-13 10:26:55.520             White              Widowed   
0   1947-12-28 02:45:40.547           Unknown              Married   
4   1949-01-10 15:37:35.543             White              Married   

   PatientLanguage  PatientPopulationPercentageBelowPoverty  
20         English                                    18.41  
1          English                                    18.20  
15       Icelandic                                    18.17  
5          English                                    83.75  
6          English                                    11.89  
7          English                                    93.60  
18         English                                    10.30  
8        Icelandic                                    19.22  
13         English                                    19.52  
3          English                                    16.32  
2          English 

In [34]:
from IPython.display import display
import pandas as pd
import numpy as np
filename = '/Users/adityasrivatsav/Documents/GitHub/PYTHON/Basics/100-patients/PatientCorePopulatedTable.txt'

df = pd.read_csv(filename, delimiter='\t')
cond = (df['PatientDateOfBirth'] > '1920-01-01') & (df['PatientDateOfBirth'] < '1950-01-01')
df_new = df[cond].reset_index(drop=True).sort_values('PatientDateOfBirth')
display(df_new)

PatientID PatientGender  \
21  DDC0BC57-7A4E-4E02-9282-177750B74FBC          Male   
1   C8556CC0-32FC-4CA5-A8CD-9CCF38816167        Female   
9   0BC491C5-5A45-4067-BD11-A78BEA00D3BE        Female   
16  53B9FFDD-F80B-43BE-93CF-C34A023EE7E9          Male   
5   DA6CECFF-DE13-4C4C-919F-64E1A2B76C9D          Male   
6   7C788499-7798-484B-A027-9FCDC4C0DADB          Male   
7   25B786AF-0F99-478C-9CFA-0EA607E45834          Male   
19  4C201C71-CCED-40D1-9642-F9C8C485B854          Male   
25  EA9B67E2-15F0-450B-A8A6-14F6E4AE3D12        Female   
8   81C5B13B-F6B2-4E57-9593-6E7E4C13B2CE        Female   
14  A0A976C8-9B30-4492-B8C4-5B25095B9192          Male   
3   FA157FA5-F488-4884-BF87-E144630D595C        Female   
2   B39DC5AC-E003-4E6A-91B6-FC07625A1285        Female   
27  1A220558-5996-43E1-AE5D-7B96180FED35          Male   
13  80D356B4-F974-441F-A5F2-F95986D119A2        Female   
18  21792512-2D40-4326-BEA2-A40127EB24FF          Male   
17  C5D09468-574F-4802-B56F-DB38F4EB1687          Male   
31  FB909FAE-72DD-4F6F-9828-D92183DF185F          Male   
10  FFCDECD6-4048-4DCB-B910-1218160005B3          Male   
29  2A5251B1-0945-47FA-A65C-7A6381562591        Female   
24  CC9CDA72-B37A-4F8F-AFE4-B08F56A183BE        Female   
20  0E0EADE8-5592-4E0B-9F88-D7596E32EE08        Female   
30  6623F5D6-D581-4268-9F9B-21612FBBF7B5        Female   
26  98F593D2-8894-49BB-93B9-5A0E2CF85E2E        Female   
23  66154E24-D3EE-4311-89DB-6195278F9B3C        Female   
12  9BBF3A51-443D-438B-9289-B98B8E0577C0          Male   
28  7A7332AD-88B1-4848-9356-E5260E477C59        Female   
22  E250799D-F6DE-4914-ADB4-B08A6E5029B9        Female   
15  E483DE6E-D4E6-47FD-905B-22EE86EC7ACE          Male   
11  967987B9-FFEF-4776-85CF-AE05CA81F583          Male   
0   FB2ABB23-C9D0-4D09-8464-49BF0B982F0F          Male   
4   1A40AF35-C6D4-4D46-B475-A15D84E8A9D5          Male   

         PatientDateOfBirth       PatientRace PatientMaritalStatus  \
21  1921-03-26 14:38:51.803             White               Single   
1   1921-04-11 11:39:49.197             White              Married   
9   1921-04-18 01:56:01.807           Unknown              Married   
16  1921-08-22 19:17:09.227             White             Divorced   
5   1924-06-27 19:37:58.823             Asian             Divorced   
6   1926-08-13 10:22:16.247             White              Married   
7   1926-08-20 00:21:38.870             White              Married   
19  1926-09-22 09:17:14.713  African American              Married   
25  1930-04-08 20:59:31.057             Asian            Separated   
8   1930-05-28 02:59:42.857             White              Married   
14  1931-05-26 14:54:15.847             Asian               Single   
3   1932-11-01 06:19:56.577             White               Single   
2   1935-11-03 21:07:09.040             White              Married   
27  1937-09-07 22:23:53.143             Asian              Married   
13  1938-03-06 18:24:18.297             White               Single   
18  1938-03-24 19:25:53.980             White               Single   
17  1939-07-07 19:39:49.753  African American              Married   
31  1940-07-15 12:18:41.080             White               Single   
10  1941-05-06 14:56:42.687             White               Single   
29  1942-01-07 16:45:33.060           Unknown              Married   
24  1942-04-14 14:01:01.130             Asian              Married   
20  1942-07-13 21:15:37.517             White              Married   
30  1943-02-17 15:36:13.787             Asian               Single   
26  1944-07-15 19:04:11.487  African American              Married   
23  1944-08-26 13:03:24.297             White             Divorced   
12  1944-11-25 06:12:56.860             White              Married   
28  1944-12-01 06:30:01.543           Unknown              Married   
22  1945-08-04 19:03:00.757             White               Single   
15  1945-11-18 04:14:31.573  African American               Single   
11  1947-02-13 1

In [2]:
from IPython.display import display
import pandas as pd
import numpy as np
filename = '/Users/adityasrivatsav/Documents/GitHub/PYTHON/Basics/100-patients/AdmissionsDiagnosesCorePopulatedTable.txt'

df = pd.read_csv(filename, delimiter='\t')

cond = (df['PrimaryDiagnosisCode'].str.startswith('M'))
df_new = df[cond].reset_index(drop=True).sort_values('PrimaryDiagnosisCode')
display(df_new)

PatientID  AdmissionID PrimaryDiagnosisCode  \
0   80AC01B2-BD55-4BE0-A59A-4024104CF4E9            2                M01.X   
78  4C201C71-CCED-40D1-9642-F9C8C485B854            5               M01.X1   
16  25B786AF-0F99-478C-9CFA-0EA607E45834            1               M01.X5   
71  21792512-2D40-4326-BEA2-A40127EB24FF            4              M01.X72   
13  DA6CECFF-DE13-4C4C-919F-64E1A2B76C9D            2               M02.35   
..                                   ...          ...                  ...   
43  9E18822E-7D13-45C7-B50E-F95CFF92BC3E            2                M90.6   
55  8856096E-E59C-4156-A767-C091AF799C80            1                M90.6   
53  135C831F-7DA5-46C0-959C-EBCBD8810B43            4              M90.632   
70  21792512-2D40-4326-BEA2-A40127EB24FF            3              M90.642   
61  C60FE675-CA52-4C55-A233-F4B27E94987F            3               M90.86   

                          PrimaryDiagnosisDescription  
0   Direct infection of joint in infectious and pa...  
78  Direct infection of shoulder joint in infectio...  
16  Direct infection of hip in infectious and para...  
71  Direct infection of left ankle and foot in inf...  
13                              Reiter's disease, hip  
..                                                ...  
43          Osteitis deformans in neoplastic diseases  
55          Osteitis deformans in neoplastic diseases  
53  Osteitis deformans in neoplastic diseases, lef...  
70  Osteitis deformans in neoplastic diseases, lef...  
61  Osteopathy in diseases classified elsewhere, l...  

[81 rows x 4 columns]

In [3]:
from IPython.display import display
import pandas as pd
import numpy as np
filename = '/Users/adityasrivatsav/Documents/GitHub/PYTHON/Basics/100-patients/AdmissionsDiagnosesCorePopulatedTable.txt'

df = pd.read_csv(filename, delimiter='\t')

cond = (df['PrimaryDiagnosisCode'].str.endswith('4'))
df_new = df[cond].reset_index(drop=True).sort_values('PrimaryDiagnosisCode')
display(df_new)

PatientID  AdmissionID PrimaryDiagnosisCode  \
21  868E700E-3C56-458F-A477-078D671DCB20            2                B33.4   
0   66154E24-D3EE-4311-89DB-6195278F9B3C            4               B97.34   
1   DA6CECFF-DE13-4C4C-919F-64E1A2B76C9D            3                C71.4   
19  6E70D84D-C75F-477C-BC37-9177C3698C66            2                D13.4   
7   79A7BA2A-D35A-4CB8-A835-6BAA13B0058C            3                  D14   
8   6D8008ED-D623-4BE4-B93B-335F9797C170            3                D41.4   
14  35FE7491-1A1D-48CB-810C-8DC2599AB3DD            2                D48.4   
3   25B786AF-0F99-478C-9CFA-0EA607E45834            5               E08.64   
11  016A590E-D093-4667-A5DA-D68EA6987D93            2               E11.64   
15  EA9B67E2-15F0-450B-A8A6-14F6E4AE3D12            1                E72.4   
22  CC12B481-B516-455B-884F-4CA900B29F2E            2                E87.4   
2   0A9BA3E4-CF3C-49C4-9774-5EEA2EE7D123            1                F31.4   
18  64182B95-EB72-4E2B-BE77-8050B71498CE            2                F45.4   
9   80D356B4-F974-441F-A5F2-F95986D119A2            1                  H34   
5   81C5B13B-F6B2-4E57-9593-6E7E4C13B2CE            1               I25.84   
6   220C8D43-1322-4A9D-B890-D426942A3649            3                  J14   
10  80D356B4-F974-441F-A5F2-F95986D119A2            2              K50.014   
20  FA157FA5-F488-4884-BF87-E144630D595C            2               M06.34   
16  6D5DCAC1-17FE-4D7C-923B-806EFBA3E6DF            3               M49.84   
17  2A5251B1-0945-47FA-A65C-7A6381562591            4                  M84   
4   F0B53A2C-98CA-415D-B928-E3FD0E52B22A            3                N18.4   
13  53B9FFDD-F80B-43BE-93CF-C34A023EE7E9            2                Q60.4   
12  3B11D6B3-A36A-4B69-A437-C29BF425A941            2                T82.4   

                          PrimaryDiagnosisDescription  
21  Hantavirus (cardio)-pulmonary syndrome [HPS] [...  
0   Human T-cell lymphotrophic virus, type II [HTL...  
1                Malignant neoplasm of occipital lobe  
19                           Benign neoplasm of liver  
7   Benign neoplasm of middle ear and respiratory ...  
8           Neoplasm of uncertain behavior of bladder  
14       Neoplasm of uncertain behavior of peritoneum  
3   Diabetes mellitus due to underlying condition ...  
11         Type 2 diabetes mellitus with hypoglycemia  
15                  Disorders of ornithine metabolism  
22                Mixed disorder of acid-base balance  
2   Bipolar disorder, current episode depressed, s...  
18    Pain disorders related to psychological factors  
9                         Retinal vascular occlusions  
5   Coronary atherosclerosis due to calcified coro...  
6              Pneumonia due to Hemophilus influenzae  
10    Crohn's disease of small intestine with abscess  
20                            Rheumatoid nodule, hand  
16  Spondylopathy in diseases classified elsewhere...  
17                     Disorder of continuity of bone  
4            Chronic kidney disease, stage 4 (severe)  
13                        Renal hypoplasia, bilateral  
12  Mechanical complication of vascular dialysis c...

In [4]:
from IPython.display import display
import pandas as pd
import numpy as np
filename = '/Users/adityasrivatsav/Documents/GitHub/PYTHON/Basics/100-patients/AdmissionsDiagnosesCorePopulatedTable.txt'

df = pd.read_csv(filename, delimiter='\t')

cond = (df['PrimaryDiagnosisCode'].str.contains('5.'))
df_new = df[cond].reset_index(drop=True).sort_values('PrimaryDiagnosisCode')
display(df_new)

PatientID  AdmissionID PrimaryDiagnosisCode  \
11  DDC0BC57-7A4E-4E02-9282-177750B74FBC            4                A52.0   
33  967987B9-FFEF-4776-85CF-AE05CA81F583            2                B95.1   
9   DDC0BC57-7A4E-4E02-9282-177750B74FBC            2               B95.62   
10  DDC0BC57-7A4E-4E02-9282-177750B74FBC            3                C05.1   
24  1A8791E3-A61C-455A-8DEE-763EB90C9B2C            3                C15.8   
..                                   ...          ...                  ...   
87  21792512-2D40-4326-BEA2-A40127EB24FF            1              O99.351   
85  714823AF-C52C-414C-B53B-C43EACD194C3            3              O9A.513   
49  53B9FFDD-F80B-43BE-93CF-C34A023EE7E9            3               O9A.53   
70  65A7FBE0-EA9F-49E9-9824-D8F3AD98DAC0            2              S35.415   
76  C8556CC0-32FC-4CA5-A8CD-9CCF38816167            2              Z95.810   

                          PrimaryDiagnosisDescription  
11        Cardiovascular and cerebrovascular syphilis  
33  Streptococcus, group B, as the cause of diseas...  
9   Methicillin resistant Staphylococcus aureus in...  
10                  Malignant neoplasm of soft palate  
24  Malignant neoplasm of overlapping sites of eso...  
..                                                ...  
87  Diseases of the nervous system complicating pr...  
85  Psychological abuse complicating pregnancy, th...  
49    Psychological abuse complicating the puerperium  
70                      Laceration of left renal vein  
76  Presence of automatic (implantable) cardiac de...  

[94 rows x 4 columns]

In [5]:
import pandas as pd
filename = '/Users/adityasrivatsav/Documents/GitHub/PYTHON/Basics/100-patients/LabsCorePopulatedTable.txt'

df = pd.read_csv(filename, delimiter="\t")
count = df.groupby("PatientID")["LabName"].count().sort_values(ascending=False)
display(count)
count[count>2000]


PatientID
80D356B4-F974-441F-A5F2-F95986D119A2    2760
25B786AF-0F99-478C-9CFA-0EA607E45834    2561
36775002-9EC3-4889-AD4F-80DC6855C8D8    2372
A0A976C8-9B30-4492-B8C4-5B25095B9192    2263
7A025E77-7832-4F53-B9A7-09A3F98AC17E    2259
                                        ... 
672D554B-D6D1-40B2-A6A4-21A4CB6B1AA6     399
C2CCB1AB-6633-4CB3-B4E8-157E6FB02376     360
8856096E-E59C-4156-A767-C091AF799C80     230
A50BE9B4-8A0B-4169-B894-F7BD86D7D90B     130
B7E9FC4C-5182-4A34-954E-CEF5FC07E96D      86
Name: LabName, Length: 100, dtype: int64

PatientID
80D356B4-F974-441F-A5F2-F95986D119A2    2760
25B786AF-0F99-478C-9CFA-0EA607E45834    2561
36775002-9EC3-4889-AD4F-80DC6855C8D8    2372
A0A976C8-9B30-4492-B8C4-5B25095B9192    2263
7A025E77-7832-4F53-B9A7-09A3F98AC17E    2259
7A7332AD-88B1-4848-9356-E5260E477C59    2257
4C201C71-CCED-40D1-9642-F9C8C485B854    2073
D8B53AA2-7953-4477-9EA4-68400EBAAC5C    2042
Name: LabName, dtype: int64

In [6]:
import pandas as pd
import numpy as np

# Create sample data
data = {
  'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
  'Score': [85, 92, 92, 78, 85, 95]
}

# Create DataFrame
df = pd.DataFrame(data)

# Sort by Score in descending order first
df_sorted = df.sort_values('Score', ascending=False)

# Add different types of ranks
df_sorted['Rank'] = df_sorted['Score'].rank(method='min', ascending=False)
df_sorted['DenseRank'] = df_sorted['Score'].rank(method='dense', ascending=False)
df_sorted['RowNumber'] = range(1, len(df_sorted) + 1)  # Add row numbers after sorting

print("\nDataFrame sorted by Score (descending):")
df_sorted


DataFrame sorted by Score (descending):


Name  Score  Rank  DenseRank  RowNumber
5    Frank     95   1.0        1.0          1
1      Bob     92   2.0        2.0          2
2  Charlie     92   2.0        2.0          3
0    Alice     85   4.0        3.0          4
4      Eve     85   4.0        3.0          5
3    David     78   6.0        4.0          6

In [7]:
import pandas as pd

# Create sample data
data = {
  'Date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02', '2024-01-03'],
  'Product': ['Laptop', 'Phone', 'Laptop', 'Phone', 'Laptop'],
  'Region': ['North', 'South', 'North', 'North', 'South'],
  'Sales': [1000, 500, 1200, 600, 900]
}

df = pd.DataFrame(data)

# Create a pivot table
pivot_table = pd.pivot_table(
    df, 
    values='Sales',
    index='Product',
    columns='Region',
    aggfunc='sum',
    fill_value=0
)

print("\nOriginal Data:")
display(df)
print("\nPivot Table:")
display(pivot_table)


Original Data:


Date Product Region  Sales
0  2024-01-01  Laptop  North   1000
1  2024-01-01   Phone  South    500
2  2024-01-02  Laptop  North   1200
3  2024-01-02   Phone  North    600
4  2024-01-03  Laptop  South    900


Pivot Table:


Region   North  South
Product              
Laptop    2200    900
Phone      600    500

In [8]:
import pandas as pd

# Create sample data
data = {
  'Date': ['2024-01-01', '2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02',
           '2024-01-02', '2024-01-03', '2024-01-03', '2024-01-03'],
  'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone',
              'Tablet', 'Laptop', 'Phone', 'Tablet'],
  'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics',
               'Electronics', 'Electronics', 'Electronics', 'Electronics'],
  'Region': ['North', 'South', 'North', 'North', 'South',
             'South', 'North', 'North', 'South'],
  'Sales': [1000, 500, 300, 1200, 600, 400, 900, 700, 350],
  'Units': [5, 10, 6, 6, 12, 8, 4, 14, 7]
}

# Create DataFrame
df = pd.DataFrame(data)

# Create a pivot table with multiple indices
pivot_table = pd.pivot_table(
  df,
  values=['Sales', 'Units'],  # Multiple values
  index=['Category', 'Product'],  # Multiple indices
  columns=['Region'],
  aggfunc={'Sales': 'sum', 'Units': 'mean'},  # Different aggregations for different values
  fill_value=0,
  margins=True  # Add totals
)

print("\nOriginal Data:")
display(df)
print("\nPivot Table with Multiple Indices:")
display(pivot_table)

# To make it more readable, we can also flatten the column headers
pivot_table.columns = [f'{col[0]}_{col[1]}' for col in pivot_table.columns]
print("\nPivot Table with Flattened Headers:")
display(pivot_table)


Original Data:


Date Product     Category Region  Sales  Units
0  2024-01-01  Laptop  Electronics  North   1000      5
1  2024-01-01   Phone  Electronics  South    500     10
2  2024-01-01  Tablet  Electronics  North    300      6
3  2024-01-02  Laptop  Electronics  North   1200      6
4  2024-01-02   Phone  Electronics  South    600     12
5  2024-01-02  Tablet  Electronics  South    400      8
6  2024-01-03  Laptop  Electronics  North    900      4
7  2024-01-03   Phone  Electronics  North    700     14
8  2024-01-03  Tablet  Electronics  South    350      7


Pivot Table with Multiple Indices:


Sales               Units             
Region                North   South   All North  South   All
Category    Product                                         
Electronics Laptop   3100.0     0.0  3100   5.0   0.00   5.0
            Phone     700.0  1100.0  1800  14.0  11.00  12.0
            Tablet    300.0   750.0  1050   6.0   7.50   7.0
All                  4100.0  1850.0  5950   7.0   9.25   8.0


Pivot Table with Flattened Headers:


Sales_North  Sales_South  Sales_All  Units_North  \
Category    Product                                                     
Electronics Laptop        3100.0          0.0       3100          5.0   
            Phone          700.0       1100.0       1800         14.0   
            Tablet         300.0        750.0       1050          6.0   
All                       4100.0       1850.0       5950          7.0   

                     Units_South  Units_All  
Category    Product                          
Electronics Laptop          0.00        5.0  
            Phone          11.00       12.0  
            Tablet          7.50        7.0  
All                         9.25        8.0

In [9]:
pivot_table = pd.pivot_table(
  df,
  values=['Sales', 'Units'],
  index=['Category', 'Product'],
  columns=['Region'],
  aggfunc={
      'Sales': ['sum', 'mean'],  # Multiple aggregations for Sales
      'Units': ['mean', 'max']   # Multiple aggregations for Units
  },
  fill_value=0
)
pivot_table

Sales                    Units                  
                            mean          sum         max        mean      
Region                     North  South North South North South North South
Category    Product                                                        
Electronics Laptop   1033.333333    0.0  3100     0     6     0   5.0   0.0
            Phone     700.000000  550.0   700  1100    14    12  14.0  11.0
            Tablet    300.000000  375.0   300   750     6     8   6.0   7.5

# 📜 NumPy Cheat Sheet

## 🔹 **Importing NumPy**
```python
import numpy as np

Creating Arrays
np.zeros((3,4))                  # Create an array of zeros
np.ones((2,3,4), dtype=np.int16)  # Create an array of ones
np.arange(10,25,5)                # Create an array of evenly spaced values
np.linspace(0,2,9)                # Evenly spaced values (number of samples)
np.full((2,2),7)                  # Create a constant array
np.eye(2)                         # Create a 2x2 identity matrix
np.random.random((2,2))           # Create an array with random values
np.empty((3,2))                   # Create an empty array

Array Mathematics
a - b         # Subtraction
np.subtract(a, b)

a + b         # Addition
np.add(a, b)

a / b         # Division
np.divide(a, b)

a * b         # Multiplication
np.multiply(a, b)

np.exp(b)     # Exponentiation
np.sqrt(b)    # Square root
np.sin(a)     # Sine
np.cos(b)     # Cosine
np.log(a)     # Logarithm

np.dot(a, b)  # Dot product

Array Indexing, Slicing, and Subsetting
a.sum()           # Sum of elements
a.min()           # Minimum value
b.max(axis=0)     # Max value along axis 0
b.cumsum(axis=1)  # Cumulative sum along axis 1
a.mean()          # Mean
np.median(a)      # Median
np.std(a)         # Standard deviation

# Slicing
a[0:2]            # Select first two elements
b[0:2, 1]         # Select items at rows 0 and 1 in column 1
a[::-1]           # Reverse array

Comparison & Boolean Indexing
a == b            # Element-wise comparison
a < 2             # Boolean mask for elements < 2
np.array_equal(a, b)  # Check if arrays are equal
a[a < 2]          # Select elements less than 2

Array Manipulation
np.transpose(b)  # Transpose array
b.T              # Alternate way to transpose

b.ravel()        # Flatten array
b.reshape(3,-2)  # Reshape array without changing data

# Adding/Removing Elements
np.append(h, g)  # Append items
np.insert(a, 1, 5)  # Insert items
np.delete(a, [1])   # Delete items

Combining Arrays
np.concatenate((a,d), axis=0)  # Concatenate arrays
np.vstack((a,b))               # Stack arrays vertically
np.hstack((e,f))               # Stack arrays horizontally
np.column_stack((a,d))         # Stack column-wise

Splitting Arrays
np.hsplit(a,3)  # Split array into 3 parts horizontally
np.vsplit(c,2)  # Split array into 2 parts vertically

Copying Arrays
h = a.view()   # Create a view of the array
np.copy(a)     # Create a copy
h = a.copy()   # Deep copy

Saving & Loading Data
np.save('my_array', a)             # Save array
np.savez('array.npz', a, b)        # Save multiple arrays
np.load('my_array.npy')            # Load saved array

np.savetxt("myarray.txt", a, delimiter=" ")   # Save as text file
np.loadtxt("myarray.txt")                     # Load text file

Sorting Arrays
a.sort()           # Sort an array
c.sort(axis=0)     # Sort along a specific axis

Inspecting Arrays
a.shape        # Array dimensions
len(a)         # Length of array
b.ndim         # Number of dimensions
e.size         # Number of elements
b.dtype        # Data type of array
b.dtype.name   # Name of data type
b.astype(int)  # Convert to different type

Data Types
np.int64      # Signed 64-bit integer
np.float32    # Floating point
np.complex    # Complex numbers
np.bool       # Boolean
np.object     # Object type
np.string_    # Fixed-length string
np.unicode_   # Fixed-length unicode

