NumPy provides a multidimensional array object.

Each object comes with an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

Basically, you can use NumPy to create ndarray (N-dimensional array) and easily manipulate the array. It is super fast because it is written in C.

How is it different from Python arrays?

Python lists can be modified – you can add and remove elements. NumPy arrays have a fixed size at creation.

Python lists can contain different data types. NumPy arrays can only have one data type. If you put in mixed types, they become a string.

NumPy arrays come prepackaged with advanced mathematical operations. The operations are super fast even on large numbers of data and they use less memory.

Why use NumPy

Most data analysis programs use NumPy to manipulate data. They might take in data as standard Python lists, but they convert it to a NumPy array and manipulate the data using NumPy routines and output the transformed data as a NumPy array.

NumPy data array is the main data type used in most scientific and mathematical Python-based packages.

In [1]:
import numpy as np
# Example
squared_values = []
for number in range(10):
    squared_values.append(number*number)
print(squared_values)

vector = np.array(range(10))
scalar = 5
print(vector * vector)
print(scalar * scalar)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[ 0  1  4  9 16 25 36 49 64 81]
25


Numpy Casting - Converts Python List to Numpy Array

In [8]:
my_list = [1, 2, 3]
print(my_list)

import numpy as np

my_vector = np.array(my_list)
print(my_vector)

my_matrix = np.array([my_list, my_list])
np.hstack([my_list, my_list])

my_nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix = np.array(my_nested_list)
print(my_matrix)

my_list1 = [[1,2], [3,4]]
my_list2 = [[5,6], [7,8]]  
np.hstack([my_list1, my_list2])   
np.vstack([my_list1, my_list2])




[1, 2, 3]
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Numpy_ Creating arrays

In [3]:
import numpy as np
my_list = range(10)
## Create the array using arrange
np.arange(10)
np.arange(0, 10)
np.arange(0, 10, 2)

## Create arrays with zeros
np.zeros(3)
np.zeros((3, 3))

## Create arrays of ones
np.ones(3)
np.ones((3, 3))
np.ones(3) *  4
## Create evenly spaced vector
### Example use case: when you have Y values for a plot but need to generate X values
### *** Includes both start an end 
# np.arange(start, end(not included), step size)
# np.linspace(start, end(included), number_of_points)
np.linspace(0, 10, 5)
np.linspace(1900, 2000, 11)

array([1900., 1910., 1920., 1930., 1940., 1950., 1960., 1970., 1980.,
       1990., 2000.])

In [4]:
#Create an indentify matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# Creating an Empty Matrix
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Creating Random Numbers
#Uniform Distribution
np.random.rand(3)
np.random.rand(3,3)
# Normal distribution
np.random.randn(3)
np.random.randn(3,3)
# Random integers
# np.random.randint(start, end(not_included), size)
np.random.randint(1,101)
np.random.randint(1,101,5)  

array([57, 62, 31, 47, 63])

In [7]:
vector = np.arange(1, 10)
print(vector.reshape(3, 3))
vector = np.arange(1,13)
print(vector.reshape(3,4))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Basic Array Operations

In [9]:
#Basic Array operations
vector = np.random.randint(1, 50, 25)
#Min
vector.min()
# Max
vector.max()
# Get location of min value
index = vector.argmin()
# Get location of max value
index = vector.argmax
#Get Shape
vector.shape

my_matrix = vector.reshape(5, 5)
my_matrix.shape

(5, 5)

Indexing a 1D Array Vector

In [10]:
vector = np.array(range(10))
# vector[index]
# vector [start:end]
# vector [:end]
# vector [start:]
# vector [start, end, step]
vector[3]
vector[3:8]
vector[:5]
vector[5:]
vector[3:9:2]
vector[-1]


9